#!/bin/sh

ARGS=$(getopt -o lm --long later,morning -n handle-deferred -- "$@")

if [ $? -ne 0 ]; then
	echo "usage: handle-deferred [--later]"
	exit 2
fi

eval set -- "$ARGS"

while :; do
	case "$1" in
		-l|--later)
			deferred_mode=later
			shift
			;;
		-m|--morning)
			deferred_mode=later
			shift
			;;
		--)	shift
			break
			;;

		*)	break
			;;
	esac
done

if [ "$deferred_mode" = later ]; then
	tag="defer:later"
elif [ "$deferred_mode" = morning ]; then
	tag="defer:morning"
else
	today=$(date +%A | tr '[:upper:]' '[:lower:]')
	tag="defer:$today"
fi

notmuch tag +inbox -${tag} -archive -- tag:${tag}
