#!/bin/sh

[ -s $HOME/.mutt/expire ] || exit 0

tmpfile=$(mktemp $HOME/.mutt/.expireXXXXXX)
trap 'rm -f $tmpfile' 0

egrep -v '^$|^#' $HOME/.mutt/expire |
while read folder expire; do
	[ -d $HOME/Mail/$folder ] || continue

	echo "Expiring messages from $folder."
	find $HOME/Mail/$folder \
		-type f -atime +$expire -print > $tmpfile

	[ -s $tmpfile ] && {
		xargs rm -f < $tmpfile
		cat $tmpfile
	}
done

